version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_historial
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: historia_clinica
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: backend_historial
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/historia_clinica
      JWT_SECRET: secreto123
      PORT: 3000

  volumes:
  pgdata:
